version: "3.9"

services:
  web:
    build: .
    container_name: shoestore_web
    command: gunicorn shoe_store.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - "8000:8000"

  db:
    image: mysql:8
    container_name: shoestore_db
    restart: always
    environment:
      MYSQL_DATABASE: shoestore
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - dbdata:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: shoestore_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - ./nginx/shoestore.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  dbdata:
  static_volume:
